<!DOCTYPE html>
<html>
  <head>
    <title>Calcolatore IVA</title>
  </head>
  <body>
    <h1>Calcolatore IVA</h1>
    <form>
      Prezzo: <input type="text" id="price"><br><br>
      Tasso IVA (%): <input type="text" id="taxRate"><br><br>
      <input type="button" value="Calcola IVA" onclick="calculateTax()"><br><br>
      IVA: <input type="text" id="taxAmount"><br><br>
      Prezzo totale: <input type="text" id="totalPrice"><br><br>
    </form>
    
    <script>
      function calculateTax() {
        // Recupera i valori dai campi di input
        var price = parseFloat(document.getElementById("price").value);
        var taxRate = parseFloat(document.getElementById("taxRate").value);
        
        // Calcola l'IVA
        var taxAmount = price * (taxRate / 100);
        
        // Calcola il prezzo totale
        var totalPrice = price + taxAmount;
        
        // Mostra il risultato nelle caselle di output
        document.getElementById("taxAmount").value = taxAmount.toFixed(2);
        document.getElementById("totalPrice").value = totalPrice.toFixed(2);
      }
    </script>
  </body>
</html>
